// ═══════════════════════════════════════════════════
// 핵심 투자 데이터 — lib/data.js
// 매분기 업데이트: 구루 포지션, 재무 기초, 기대값
// ═══════════════════════════════════════════════════
import { universeMeta } from './universe';
import FUNDAMENTALS from './fundamentals_cache.json';

export const STOCK_UNIVERSE = {
  // ── 보유 종목 ────────────────────────────────────
  GOOGL: {
    name: '알파벳', nameEn: 'Alphabet Inc.', flag: '🇺🇸',
    sector: 'AI·클라우드', type: 'portfolio',
    exchange: 'NASDAQ',
    // 역산 DCF 기대값 (모부신 방법론)
    fair_value: 392, fair_low: 340, fair_high: 460,
    // 재무 기초 (FY2025 기준, 분기마다 업데이트)
    eps_ttm: 13.11, revenue_ttm: 422.5e9,
    revenue_per_share: 34.6, bvps: 22.4,
    fcf_annual: 73e9, sbc_annual: 22e9,
    shares_out: 12.2e9, net_cash: 31e9,
    // 품질 (SEC EDGAR 기반 분기 계산)
    piotroski: 8, beneish_m: -2.1, altman_z: 8.4,
    roic: 28.34, wacc: 9.06,
    // 모멘텀
    mom_12_1: 18.5, // 12-1M 가격 모멘텀 %
    erv_score: 0.3, // 어닝 리비전 (상향비율 - 하향비율)
    // 텐베거 지표
    rule_of_40: null, // 성숙 기업, 별도 계산 안 함
    rev_growth_yoy: 14.5, rev_growth_accel: 2.1,
    gross_margin: 58.1, gm_trend: 1.2, // 전분기 대비
    // 구루
    guru_cost: 390, guru_cost_type: '추정치',
    guru_note: '버크셔 6월 $100억 신규+TCI+뢰브 클러스터',
    // 세그먼트 (Finnhub 자동, 아래는 초기값)
    segments: [
      { name: 'Search·광고', pct: 72, growth: 14.0, trend: 'stable' },
      { name: 'Google Cloud', pct: 11, growth: 48.0, trend: 'accel' },
      { name: 'YouTube', pct: 11, growth: 8.0, trend: 'stable' },
      { name: 'Other Bets', pct: 6, growth: -2.0, trend: 'down' },
    ],
    geo: [
      { name: '미국', pct: 48 }, { name: '유럽', pct: 26 },
      { name: 'APAC', pct: 16 }, { name: '기타', pct: 10 },
    ],
    key_risk: 'DOJ 반독점 소송 진행 중. 검색 시장점유율 AI 챗봇에 위협.',
    key_oppty: 'Cloud +48% 가속. Waymo 자율주행. Gemini AI 수익화.',
    event_date: null, // 다음 실적 발표일
    // 역사 PE (초기값, Yahoo Finance에서 자동 갱신)
    pe_hist_avg_5y: 23.5, pe_hist_avg_10y: 22.3,
    pe_hist_min_5y: 17.2, pe_hist_max_5y: 36.1,
  },

  TSLA: {
    name: '테슬라', nameEn: 'Tesla Inc.', flag: '🇺🇸',
    sector: 'EV·로보틱스', type: 'locked',
    exchange: 'NASDAQ',
    locked_note: '10년 장기 보유 예외 종목',
    fair_value: 463, fair_low: 200, fair_high: 950,
    eps_ttm: 1.8, revenue_ttm: 97.7e9,
    revenue_per_share: 31.5, bvps: 18.6,
    fcf_annual: 1.4e9, sbc_annual: 5.4e9,
    shares_out: 3.2e9, net_cash: 18e9,
    piotroski: 6, beneish_m: -1.9, altman_z: 4.2,
    roic: 11.2, wacc: 13.0,
    guru_cost: null, guru_note: '로보택시·옵티머스 논제',
    segments: [
      { name: '자동차 판매', pct: 80, growth: 6.0, trend: 'stable' },
      { name: '에너지·Megapack', pct: 10, growth: 45.0, trend: 'accel' },
      { name: 'FSD·서비스', pct: 10, growth: 51.0, trend: 'accel' },
    ],
    pe_hist_avg_5y: 58.0, pe_hist_avg_10y: null,
  },

  AAPL: {
    name: '애플', nameEn: 'Apple Inc.', flag: '🇺🇸',
    sector: '소비자 기술', type: 'portfolio',
    exchange: 'NASDAQ',
    fair_value: 322, fair_low: 260, fair_high: 420,
    eps_ttm: 8.27, revenue_ttm: 391e9,
    revenue_per_share: 25.8, bvps: 4.2,
    fcf_annual: 102e9, sbc_annual: 11.7e9,
    shares_out: 15.1e9, net_cash: -68e9,
    piotroski: 7, beneish_m: -2.4, altman_z: 5.8,
    roic: 54.3, wacc: 9.5,
    mom_12_1: 12.3, erv_score: 0.15,
    rev_growth_yoy: 5.1, gross_margin: 46.2, gm_trend: 0.8,
    guru_cost: 165, guru_cost_type: '확인값(추정)',
    guru_note: '버핏 21.99% 보유. 비중 서서히 축소 중.',
    segments: [
      { name: 'iPhone', pct: 52, growth: 1.0, trend: 'stable' },
      { name: 'Services', pct: 28, growth: 13.0, trend: 'accel' },
      { name: 'Mac', pct: 10, growth: 2.0, trend: 'stable' },
      { name: 'iPad', pct: 6, growth: -5.0, trend: 'down' },
      { name: '웨어러블', pct: 4, growth: -7.0, trend: 'down' },
    ],
    geo: [
      { name: '미국', pct: 44 }, { name: '유럽', pct: 23 },
      { name: '중화권', pct: 17 }, { name: '기타', pct: 16 },
    ],
    key_risk: 'DOJ 앱스토어 반독점. EU DMA 규제. 중화권 관세 리스크.',
    key_oppty: 'Apple Intelligence 업그레이드 사이클. Services 마진 75%+.',
    pe_hist_avg_5y: 28.2, pe_hist_avg_10y: 22.1,
    pe_hist_min_5y: 18.5, pe_hist_max_5y: 44.0,
  },

  AMZN: {
    name: '아마존', nameEn: 'Amazon.com', flag: '🇺🇸',
    sector: '클라우드·이커머스', type: 'portfolio',
    exchange: 'NASDAQ',
    fair_value: 296, fair_low: 215, fair_high: 415,
    eps_ttm: 5.53, revenue_ttm: 638e9,
    revenue_per_share: 59.8, bvps: 26.1,
    fcf_annual: 1.2e9, sbc_annual: 24e9, // CapEx로 FCF 압박
    shares_out: 10.7e9, net_cash: -58e9,
    piotroski: 7, beneish_m: -1.8, altman_z: 3.2,
    roic: 16.8, wacc: 10.2,
    mom_12_1: 8.2, erv_score: 0.22,
    rev_growth_yoy: 11.5, gross_margin: 48.2, gm_trend: 2.1,
    guru_cost: 209, guru_cost_type: '역산 추정',
    guru_note: '애크먼+테퍼 동시 매수 $209 (Q1 2026)',
    segments: [
      { name: 'AWS', pct: 15, growth: 28.0, trend: 'accel' },
      { name: '북미 리테일', pct: 42, growth: 5.0, trend: 'stable' },
      { name: '광고', pct: 9, growth: 19.0, trend: 'accel' },
      { name: '구독(Prime)', pct: 7, growth: 8.0, trend: 'stable' },
      { name: '해외', pct: 27, growth: 9.0, trend: 'stable' },
    ],
    key_risk: 'CapEx $200B으로 FCF 소멸. 규제 압박(EU·FTC).',
    key_oppty: '2027년 CapEx 사이클 종료 후 FCF 폭발적 회복 예상.',
    pe_hist_avg_5y: 52.1, pe_hist_avg_10y: 85.3,
  },

  AVGO: {
    name: '브로드컴', nameEn: 'Broadcom Inc.', flag: '🇺🇸',
    sector: 'AI 반도체', type: 'portfolio',
    exchange: 'NASDAQ',
    fair_value: 524, fair_low: 380, fair_high: 720,
    eps_ttm: 7.26, revenue_ttm: 51.6e9,
    revenue_per_share: 10.8, bvps: 8.2,
    fcf_annual: 22e9, sbc_annual: 3.2e9,
    shares_out: 4.74e9, net_cash: -60e9,
    piotroski: 7, beneish_m: -2.0, altman_z: 2.8,
    roic: 22.1, wacc: 9.8,
    mom_12_1: 22.1, erv_score: 0.35,
    rev_growth_yoy: 38.4, gross_margin: 69.0, gm_trend: 1.8,
    guru_cost: 310, guru_cost_type: '역산 추정',
    guru_note: '드러켄밀러 Q1 신규 196K주. Apollo $350억 투자.',
    segments: [
      { name: 'AI 커스텀칩(XPU)', pct: 21, growth: 143.0, trend: 'accel' },
      { name: '반도체(기타)', pct: 32, growth: 8.0, trend: 'stable' },
      { name: 'VMware 소프트웨어', pct: 47, growth: 9.0, trend: 'stable' },
    ],
    event_date: '2026-09-03', // 다음 분기 실적
    key_risk: '소프트웨어 세그먼트 성장 둔화 우려. VMware 통합 리스크.',
    key_oppty: 'Google·Meta AI칩 수요. Q3 가이던스 $294억(+84% YoY).',
    pe_hist_avg_5y: 38.2, pe_hist_avg_10y: 32.1,
  },

  COIN: {
    name: '코인베이스', nameEn: 'Coinbase Global', flag: '🇺🇸',
    sector: '크립토 인프라', type: 'portfolio',
    exchange: 'NASDAQ',
    fair_value: 197, fair_low: 70, fair_high: 420,
    eps_ttm: -0.52, revenue_ttm: 7.2e9,
    revenue_per_share: 17.4, bvps: 14.2,
    fcf_annual: 1.8e9, sbc_annual: 0.8e9,
    shares_out: 0.415e9, net_cash: 8e9,
    piotroski: 5, beneish_m: -1.6, altman_z: null,
    roic: 8.2, wacc: 12.0,
    mom_12_1: -8.4, erv_score: -0.15,
    rev_growth_yoy: 28.5, gross_margin: 42.1, gm_trend: -0.5,
    guru_cost: 175, guru_cost_type: '평단 추정',
    guru_note: 'GENIUS Act 스테이블코인 구조적 성장 논제 유효.',
    segments: [
      { name: '거래 수수료', pct: 50, growth: 25.0, trend: 'volatile' },
      { name: '스테이블코인(USDC)', pct: 19, growth: 48.0, trend: 'accel' },
      { name: '블록체인 서비스', pct: 15, growth: 35.0, trend: 'accel' },
      { name: '기타', pct: 16, growth: 10.0, trend: 'stable' },
    ],
    key_risk: 'BTC $60K 이탈. 거래량 사이클 의존. Visa·Mastercard 스테이블코인 경쟁.',
    key_oppty: '스테이블코인 GENIUS Act 법제화. 기관 채택 가속.',
    pe_hist_avg_5y: null,
  },

  IREN: {
    name: '아이렌', nameEn: 'IREN Ltd', flag: '🇦🇺',
    sector: 'AI클라우드·BTC채굴', type: 'portfolio',
    exchange: 'NASDAQ',
    fair_value: 78, fair_low: 20, fair_high: 150,
    eps_ttm: -0.8, revenue_ttm: 0.18e9,
    revenue_per_share: 0.52, bvps: 2.1,
    fcf_annual: -0.05e9, sbc_annual: 0.02e9,
    shares_out: 0.345e9, net_cash: 0.5e9,
    piotroski: 4, beneish_m: null, altman_z: null,
    roic: -5.2, wacc: 15.0,
    mom_12_1: 45.2, erv_score: 0.1,
    rev_growth_yoy: 95.0, gross_margin: 28.0, gm_trend: 3.2,
    rule_of_40: -12, // 적자로 Rule of 40 낮음
    guru_cost: 45, guru_cost_type: '추정 평균',
    guru_note: 'Cantor Fitzgerald 목표가 $99. MS $36억 계약. Dell Blackwell.',
    segments: [
      { name: 'AI GPU-as-a-Service', pct: 55, growth: 180.0, trend: 'accel' },
      { name: 'BTC 채굴', pct: 45, growth: 30.0, trend: 'volatile' },
    ],
    key_risk: 'BTC -60% 시 주가 -70% 가능. 고위험. AI 버블 리스크.',
    key_oppty: 'AI GPU 수요 폭발. MS·Dell 대형 계약.',
    pe_hist_avg_5y: null,
  },

  NTRA: {
    name: '나테라', nameEn: 'Natera Inc.', flag: '🇺🇸',
    sector: '헬스케어·진단', type: 'portfolio',
    exchange: 'NASDAQ',
    fair_value: 249, fair_low: 122, fair_high: 390,
    eps_ttm: -2.1, revenue_ttm: 2.6e9,
    revenue_per_share: 10.8, bvps: 3.4,
    fcf_annual: 0.1e9, sbc_annual: 0.18e9,
    shares_out: 0.241e9, net_cash: 1.2e9,
    piotroski: 7, beneish_m: -2.3, altman_z: null,
    roic: -4.8, wacc: 11.5,
    mom_12_1: 12.8, erv_score: 0.41,
    rev_growth_yoy: 39.0, gross_margin: 62.0, gm_trend: 5.1,
    rule_of_40: 34, // 적자지만 62+39=101은 매출총이익+성장 기준
    tam_penetration: 3.2, // TAM 대비 침투율 %
    guru_cost: 86, guru_cost_type: '역산 추정(4년평균)',
    guru_note: '드러켄밀러 4년 18.1% 보유. 코트+1446%. 공매도 15%+.',
    segments: [
      { name: 'Signatera(암재발)', pct: 45, growth: 54.0, trend: 'accel' },
      { name: 'Panorama(산전)', pct: 40, growth: 25.0, trend: 'stable' },
      { name: 'Prospera(이식)', pct: 15, growth: 38.0, trend: 'accel' },
    ],
    key_risk: 'GAAP 적자. 보험 커버 리스크. Guardant Health 경쟁.',
    key_oppty: '첫 1분기 100만건 돌파. 일본 진출 2026. FCF 흑자 전환.',
    pe_hist_avg_5y: null,
    // 텐베거 지표
    ten_bagger_score: 82,
    ten_narrative: 'Signatera가 21세기 PSA 검사 표준이 된다면 TAM $300억+ 중 현재 침투율 3%. 드러켄밀러 4년 보유가 이 논리 확인.',
  },

  // ── 트래킹 종목 ───────────────────────────────────
  NVDA: {
    name: '엔비디아', nameEn: 'NVIDIA Corp.', flag: '🇺🇸',
    sector: 'AI 반도체', type: 'watch',
    exchange: 'NASDAQ',
    fair_value: 268, fair_low: 152, fair_high: 390,
    eps_ttm: 3.58, revenue_ttm: 113e9,
    revenue_per_share: 4.62, bvps: 2.8,
    fcf_annual: 61e9, sbc_annual: 4.8e9,
    shares_out: 24.4e9, net_cash: 34e9,
    piotroski: 8, beneish_m: -2.5, altman_z: 12.1,
    roic: 62.5, wacc: 10.5,
    mom_12_1: 28.4, erv_score: 0.58,
    rev_growth_yoy: 82.0, gross_margin: 75.0, gm_trend: 2.8,
    rule_of_40: 75,
    guru_cost: 185, guru_cost_type: '역산 추정',
    guru_note: 'CUDA 독점 해자. Blackwell 램프업. ATH 근처 주의.',
    segments: [
      { name: '데이터센터', pct: 87, growth: 95.0, trend: 'accel' },
      { name: '게이밍', pct: 9, growth: 8.0, trend: 'stable' },
      { name: '자동차·기타', pct: 4, growth: 25.0, trend: 'accel' },
    ],
    key_risk: 'ATH 근처. AMD·자체칩(TPU·XPU) 경쟁. CapEx 삭감 리스크.',
    key_oppty: 'Rubin 차세대 칩. 로보틱스 AI 추가 수요.',
    pe_hist_avg_5y: 52.1, pe_hist_avg_10y: 38.4,
  },

  META: {
    name: '메타', nameEn: 'Meta Platforms', flag: '🇺🇸',
    sector: '소셜·AI', type: 'watch',
    exchange: 'NASDAQ',
    fair_value: 694, fair_low: 396, fair_high: 960,
    eps_ttm: 23.6, revenue_ttm: 164.5e9,
    revenue_per_share: 64.2, bvps: 52.1,
    fcf_annual: 52e9, sbc_annual: 15e9,
    shares_out: 2.56e9, net_cash: 42e9,
    piotroski: 8, beneish_m: -2.1, altman_z: 9.2,
    roic: 34.2, wacc: 9.8,
    mom_12_1: -8.1, erv_score: 0.28,
    rev_growth_yoy: 22.5, gross_margin: 81.0, gm_trend: 1.2,
    rule_of_40: 81,
    guru_cost: 650, guru_cost_type: '역산 추정',
    guru_note: '애크먼 Q1 신규. 뢰브 Q1 신규. ATH $796 대비 -28%.',
    segments: [
      { name: 'Facebook·Instagram 광고', pct: 80, growth: 20.0, trend: 'stable' },
      { name: 'WhatsApp·기타', pct: 17, growth: 28.0, trend: 'accel' },
      { name: 'Reality Labs', pct: 3, growth: -5.0, trend: 'down' },
    ],
    key_risk: 'Reality Labs 연 -$50억. CapEx $60~65B 부담. EU 규제.',
    key_oppty: 'AI 광고 효율 +20%. Llama 오픈소스 생태계. Threads.',
    pe_hist_avg_5y: 22.8, pe_hist_avg_10y: 19.2,
  },

  MSFT: {
    name: '마이크로소프트', nameEn: 'Microsoft Corp.', flag: '🇺🇸',
    sector: '클라우드·AI', type: 'watch',
    exchange: 'NASDAQ',
    fair_value: 479, fair_low: 310, fair_high: 646,
    eps_ttm: 13.1, revenue_ttm: 261e9,
    revenue_per_share: 35.1, bvps: 28.4,
    fcf_annual: 74e9, sbc_annual: 9.8e9,
    shares_out: 7.44e9, net_cash: 28e9,
    piotroski: 8, beneish_m: -2.4, altman_z: 8.9,
    roic: 25.8, wacc: 9.2,
    mom_12_1: 5.2, erv_score: 0.32,
    rev_growth_yoy: 15.8, gross_margin: 70.0, gm_trend: 0.8,
    rule_of_40: 71,
    guru_cost: 435.22, guru_cost_type: '확인값',
    guru_note: '애크먼 Q1 2026 신규 매수 $435.22 확인됨. 15.26% 비중.',
    segments: [
      { name: 'Azure·클라우드', pct: 35, growth: 40.0, trend: 'accel' },
      { name: 'Office·Copilot', pct: 30, growth: 12.0, trend: 'stable' },
      { name: 'Xbox·기타', pct: 35, growth: 8.0, trend: 'stable' },
    ],
    key_risk: 'OpenAI 독점 관계 변화 리스크. 높은 밸류에이션.',
    key_oppty: 'Azure +40%. Copilot $50→구독 인상. AI 에이전트 Enterprise.',
    pe_hist_avg_5y: 33.2, pe_hist_avg_10y: 28.8,
  },

  ORCL: {
    name: '오라클', nameEn: 'Oracle Corp.', flag: '🇺🇸',
    sector: '클라우드·DB', type: 'watch',
    exchange: 'NYSE',
    fair_value: 240, fair_low: 147, fair_high: 320,
    eps_ttm: 8.05, revenue_ttm: 67.4e9,
    revenue_per_share: 23.8, bvps: -4.2, // 부채 많아 음수
    fcf_annual: -5e9, sbc_annual: 5e9, // CapEx로 FCF 마이너스
    shares_out: 2.84e9, net_cash: -135e9,
    piotroski: 6, beneish_m: -1.9, altman_z: null,
    roic: 18.5, wacc: 9.0,
    mom_12_1: 8.8, erv_score: 0.25,
    rev_growth_yoy: 17.2, gross_margin: 71.0, gm_trend: 0.4,
    guru_cost: 206, guru_cost_type: '역산 추정',
    guru_note: 'RPO $6,380억. AI계약 $670억/분기. FY27 $900억 가이던스.',
    segments: [
      { name: 'OCI 클라우드', pct: 20, growth: 84.0, trend: 'accel' },
      { name: '클라우드 서비스', pct: 35, growth: 25.0, trend: 'accel' },
      { name: '라이선스·서포트', pct: 40, growth: 3.0, trend: 'stable' },
      { name: '하드웨어', pct: 5, growth: -8.0, trend: 'down' },
    ],
    key_risk: '부채 $1,350억. CapEx 사이클로 FCF 마이너스. 신용 리스크.',
    key_oppty: 'RPO $6,380억 = 매출의 9.5배. AI 인프라 수요 폭발.',
    pe_hist_avg_5y: 28.4, pe_hist_avg_10y: 22.1,
    event_date: '2026-09-09',
  },

  VRT: {
    name: '버티브', nameEn: 'Vertiv Holdings', flag: '🇺🇸',
    sector: 'AI 인프라(전력·냉각)', type: 'watch',
    exchange: 'NYSE',
    fair_value: 419, fair_low: 210, fair_high: 620,
    eps_ttm: 2.85, revenue_ttm: 10.2e9,
    revenue_per_share: 7.72, bvps: 8.4,
    fcf_annual: 1.2e9, sbc_annual: 0.15e9,
    shares_out: 1.32e9, net_cash: -4e9,
    piotroski: 7, beneish_m: -2.0, altman_z: 3.1,
    roic: 18.2, wacc: 10.8,
    mom_12_1: 18.2, erv_score: 0.44,
    rev_growth_yoy: 30.0, gross_margin: 38.0, gm_trend: 2.1,
    rule_of_40: 42,
    guru_cost: 355, guru_cost_type: '추정',
    guru_note: '백로그 $150억(+109% YoY). FY26 $135~140억 가이던스.',
    segments: [
      { name: '제품(전력·냉각)', pct: 70, growth: 35.0, trend: 'accel' },
      { name: '서비스', pct: 30, growth: 18.0, trend: 'stable' },
    ],
    key_risk: 'AI CapEx 삭감 시 수요 감소. 경쟁사 가격 공세.',
    key_oppty: 'AI 데이터센터 불가침 인프라. 백로그 2년치 이상.',
    pe_hist_avg_5y: 32.1, pe_hist_avg_10y: null,
  },

  MU: {
    name: '마이크론', nameEn: 'Micron Technology', flag: '🇺🇸',
    sector: 'HBM 메모리', type: 'watch',
    exchange: 'NASDAQ',
    fair_value: 937, fair_low: 500, fair_high: 1490,
    eps_ttm: 9.18, revenue_ttm: 58.1e9,
    revenue_per_share: 52.5, bvps: 38.2,
    fcf_annual: 8e9, sbc_annual: 0.8e9,
    shares_out: 1.11e9, net_cash: 8e9,
    piotroski: 7, beneish_m: -1.8, altman_z: 4.8,
    roic: 15.2, wacc: 10.5,
    mom_12_1: 42.1, erv_score: 0.48,
    rev_growth_yoy: 45.0, gross_margin: 38.0, gm_trend: 8.2,
    guru_cost: 850, guru_cost_type: '추정',
    guru_note: '3주 전 $757에서 $1,035로 +37% 급등. 기대값 이미 초과.',
    segments: [
      { name: 'DRAM(HBM포함)', pct: 65, growth: 55.0, trend: 'accel' },
      { name: 'NAND', pct: 30, growth: 28.0, trend: 'stable' },
      { name: '기타', pct: 5, growth: 10.0, trend: 'stable' },
    ],
    key_risk: '반도체 사이클. 삼성 HBM 램프업. 현재 기대값 초과 고평가.',
    key_oppty: 'HBM4 독점. AI 메모리 수요 장기 강세.',
    pe_hist_avg_5y: 28.4, pe_hist_avg_10y: null,
  },

  AMD: {
    name: 'AMD', nameEn: 'Advanced Micro Devices', flag: '🇺🇸',
    sector: 'AI 반도체', type: 'watch',
    exchange: 'NASDAQ',
    fair_value: 195, fair_low: 120, fair_high: 280,
    eps_ttm: 1.60, revenue_ttm: 25.8e9,
    revenue_per_share: 15.8, bvps: 46.2,
    fcf_annual: 2.8e9, sbc_annual: 1.5e9,
    shares_out: 1.62e9, net_cash: 1.2e9,
    piotroski: 6, beneish_m: -2.0, altman_z: 4.2,
    roic: 4.8, wacc: 10.5,
    mom_12_1: 5.2, erv_score: 0.18,
    rev_growth_yoy: 24.0, gross_margin: 53.0, gm_trend: 1.5,
    rule_of_40: 42,
    guru_cost: 165, guru_cost_type: '추정',
    guru_note: 'MI300X AI GPU로 NVDA 점유율 잠식. 데이터센터 가속 성장.',
    segments: [
      { name: '데이터센터(AI GPU)', pct: 50, growth: 80.0, trend: 'accel' },
      { name: '클라이언트(CPU)', pct: 25, growth: 10.0, trend: 'stable' },
      { name: '게이밍·임베디드', pct: 25, growth: -15.0, trend: 'down' },
    ],
    key_risk: 'NVDA CUDA 생태계 우위. 데이터센터 고객 편중 리스크.',
    key_oppty: 'MI300X·MI400 AI 가속기 점유율 확대. EPYC 서버 점유율 30%+.',
    pe_hist_avg_5y: 42.0,
  },

  PLTR: {
    name: '팔란티어', nameEn: 'Palantir Technologies', flag: '🇺🇸',
    sector: 'AI 소프트웨어', type: 'watch',
    exchange: 'NASDAQ',
    fair_value: 38, fair_low: 20, fair_high: 70,
    eps_ttm: 0.16, revenue_ttm: 2.87e9,
    revenue_per_share: 1.19, bvps: 4.8,
    fcf_annual: 1.0e9, sbc_annual: 0.54e9,
    shares_out: 2.41e9, net_cash: 3.8e9,
    piotroski: 7, beneish_m: -1.9, altman_z: null,
    roic: 6.8, wacc: 11.0,
    mom_12_1: 35.2, erv_score: 0.42,
    rev_growth_yoy: 36.0, gross_margin: 80.0, gm_trend: 0.5,
    rule_of_40: 76,
    tam_penetration: 4.0,
    guru_cost: null, guru_cost_type: '추정',
    guru_note: 'AIP·GOTHAM 미국 상업 +71% YoY. 정부 AI 독점 지위.',
    segments: [
      { name: '미국 상업(AIP)', pct: 42, growth: 71.0, trend: 'accel' },
      { name: '미국 정부(GOTHAM)', pct: 35, growth: 21.0, trend: 'stable' },
      { name: '해외', pct: 23, growth: 5.0, trend: 'stable' },
    ],
    key_risk: '밸류에이션 고평가 (PSR 30x+). SBC 비율 높음.',
    key_oppty: 'AIP 플랫폼 AI 소프트웨어 독점. 국방부 프라임 포지션.',
    pe_hist_avg_5y: null,
    ten_bagger_score: 68,
    ten_narrative: 'AI 플랫폼 소프트웨어 독점 포지션. 정부+상업 듀얼 수요로 지속 성장 가능.',
    rev_growth_accel: 3.2,
  },

  ARM: {
    name: 'ARM홀딩스', nameEn: 'Arm Holdings', flag: '🇬🇧',
    sector: 'AI 반도체 설계', type: 'watch',
    exchange: 'NASDAQ',
    fair_value: 92, fair_low: 55, fair_high: 150,
    eps_ttm: 1.31, revenue_ttm: 4.0e9,
    revenue_per_share: 3.86, bvps: 12.4,
    fcf_annual: 1.6e9, sbc_annual: 0.28e9,
    shares_out: 1.04e9, net_cash: 1.5e9,
    piotroski: 7, beneish_m: -2.1, altman_z: null,
    roic: 18.5, wacc: 10.0,
    mom_12_1: 12.8, erv_score: 0.35,
    rev_growth_yoy: 48.0, gross_margin: 98.0, gm_trend: 0.2,
    rule_of_40: 80, rev_growth_accel: 2.5,
    guru_cost: null, guru_cost_type: '추정',
    guru_note: 'AI 모바일·엣지 칩 설계 표준. Apple·Qualcomm·NVDA 전부 ARM.',
    segments: [
      { name: '로열티(칩 판매)', pct: 60, growth: 55.0, trend: 'accel' },
      { name: '라이선스', pct: 40, growth: 40.0, trend: 'accel' },
    ],
    key_risk: '손정의(SoftBank) 90% 지분. 중국 수출 규제 리스크.',
    key_oppty: 'AI PC·서버 ARM 전환 가속. 로열티 단가 상승 사이클.',
    pe_hist_avg_5y: null,
  },

  SMCI: {
    name: '슈퍼마이크로', nameEn: 'Super Micro Computer', flag: '🇺🇸',
    sector: 'AI 서버 인프라', type: 'watch',
    exchange: 'NASDAQ',
    fair_value: 55, fair_low: 25, fair_high: 110,
    eps_ttm: 1.42, revenue_ttm: 15.0e9,
    revenue_per_share: 24.8, bvps: 22.1,
    fcf_annual: -0.5e9, sbc_annual: 0.15e9,
    shares_out: 0.607e9, net_cash: -1.2e9,
    piotroski: 5, beneish_m: -1.5, altman_z: 2.8,
    roic: 8.2, wacc: 12.0,
    mom_12_1: -28.4, erv_score: -0.22,
    rev_growth_yoy: 110.0, gross_margin: 14.5, gm_trend: -1.2, rev_growth_accel: -5.0,
    guru_cost: null, guru_cost_type: '추정',
    guru_note: '회계 지연·감사인 교체로 고위험. AI 서버 직접 수혜지만 리스크 높음.',
    segments: [
      { name: 'AI 서버(H100/H200)', pct: 80, growth: 120.0, trend: 'accel' },
      { name: '스토리지·기타', pct: 20, growth: 15.0, trend: 'stable' },
    ],
    key_risk: '회계 이슈. 낮은 GM. NVDA 의존도 80%+. 단기 고변동성.',
    key_oppty: 'AI 데이터센터 랙 솔루션 수혜. 직접 납품 채널.',
    pe_hist_avg_5y: null,
  },

  TSM: {
    name: 'TSMC', nameEn: 'Taiwan Semiconductor', flag: '🇹🇼',
    sector: 'AI 반도체 파운드리', type: 'watch',
    exchange: 'NYSE',
    fair_value: 235, fair_low: 165, fair_high: 310,
    eps_ttm: 8.12, revenue_ttm: 87.0e9,
    revenue_per_share: 33.5, bvps: 52.4,
    fcf_annual: 18e9, sbc_annual: 0.8e9,
    shares_out: 2.6e9, net_cash: 28e9,
    piotroski: 8, beneish_m: -2.3, altman_z: 6.2,
    roic: 22.8, wacc: 9.5,
    mom_12_1: 28.1, erv_score: 0.45,
    rev_growth_yoy: 38.0, gross_margin: 56.0, gm_trend: 2.8, rev_growth_accel: 3.5,
    rule_of_40: 60,
    guru_cost: 175, guru_cost_type: '역산 추정',
    guru_note: '버핏 2023 매도 후 AI 칩 독점으로 재평가. 3nm·2nm 독점.',
    segments: [
      { name: '3nm 이하(AI칩)', pct: 26, growth: 90.0, trend: 'accel' },
      { name: '5nm', pct: 22, growth: 20.0, trend: 'stable' },
      { name: '7nm 이상', pct: 52, growth: 5.0, trend: 'stable' },
    ],
    key_risk: '대만 지정학 리스크. 애리조나 팹 비용 초과.',
    key_oppty: 'AI 칩 독점 파운드리. CoWoS 패키징 병목 해소 수혜.',
    pe_hist_avg_5y: 18.5, pe_hist_avg_10y: 16.2,
  },

  ASML: {
    name: 'ASML', nameEn: 'ASML Holding', flag: '🇳🇱',
    sector: '반도체 장비', type: 'watch',
    exchange: 'NASDAQ',
    fair_value: 1050, fair_low: 700, fair_high: 1400,
    eps_ttm: 22.8, revenue_ttm: 28.3e9,
    revenue_per_share: 71.2, bvps: 48.2,
    fcf_annual: 5.8e9, sbc_annual: 0.6e9,
    shares_out: 0.397e9, net_cash: 1.8e9,
    piotroski: 8, beneish_m: -2.4, altman_z: 7.8,
    roic: 32.5, wacc: 8.8,
    mom_12_1: 8.4, erv_score: 0.28,
    rev_growth_yoy: 15.0, gross_margin: 51.0, gm_trend: 0.8, rev_growth_accel: 1.5,
    rule_of_40: 48,
    guru_cost: 880, guru_cost_type: '역산 추정',
    guru_note: '세계 유일 EUV 장비 독점. AI 칩 수요로 2025-2030 성장 가시성 확보.',
    segments: [
      { name: 'EUV 장비', pct: 55, growth: 22.0, trend: 'accel' },
      { name: 'DUV 장비', pct: 30, growth: 5.0, trend: 'stable' },
      { name: '서비스·업그레이드', pct: 15, growth: 18.0, trend: 'stable' },
    ],
    key_risk: '중국 수출 규제 (매출 15% 위험). 반도체 사이클 하강.',
    key_oppty: 'EUV 독점 글로벌 해자. High-NA EUV 신제품 사이클.',
    pe_hist_avg_5y: 42.0, pe_hist_avg_10y: 32.5,
  },

  CRWD: {
    name: '크라우드스트라이크', nameEn: 'CrowdStrike Holdings', flag: '🇺🇸',
    sector: '사이버보안 AI', type: 'watch',
    exchange: 'NASDAQ',
    // 2026-07-02 4:1 액면분할 반영 완료
    fair_value: 108, fair_low: 68, fair_high: 155,
    eps_ttm: 0.06, revenue_ttm: 3.95e9,
    revenue_per_share: 3.95, bvps: 4.55,
    fcf_annual: 1.0e9, sbc_annual: 0.72e9,
    shares_out: 1.0e9, net_cash: 3.5e9,
    piotroski: 6, beneish_m: -2.0, altman_z: null,
    roic: 5.2, wacc: 11.5,
    mom_12_1: -5.2, erv_score: 0.22,
    rev_growth_yoy: 33.0, gross_margin: 78.0, gm_trend: 0.8, rev_growth_accel: 1.0,
    rule_of_40: 65,
    guru_cost: 95, guru_cost_type: '추정',
    guru_note: '2024년 7월 IT 대란 후 주가 -40%. 회복 중. ARR $4.2B+ 성장.',
    segments: [
      { name: '구독 ARR', pct: 95, growth: 34.0, trend: 'accel' },
      { name: '서비스', pct: 5, growth: 10.0, trend: 'stable' },
    ],
    key_risk: '2024 IT 대란 신뢰도 훼손. 고PSR 밸류에이션.',
    key_oppty: 'AI 네이티브 보안 플랫폼 독보적 위치. Charlotte AI.',
    pe_hist_avg_5y: null,
  },

  SNOW: {
    name: '스노우플레이크', nameEn: 'Snowflake Inc.', flag: '🇺🇸',
    sector: '데이터 클라우드', type: 'watch',
    exchange: 'NYSE',
    fair_value: 210, fair_low: 120, fair_high: 320,
    eps_ttm: -1.74, revenue_ttm: 3.53e9,
    revenue_per_share: 10.8, bvps: 18.5,
    fcf_annual: 0.8e9, sbc_annual: 1.2e9,
    shares_out: 0.328e9, net_cash: 4.2e9,
    piotroski: 5, beneish_m: -1.8, altman_z: null,
    roic: -8.2, wacc: 12.0,
    mom_12_1: -12.4, erv_score: -0.08,
    rev_growth_yoy: 29.0, gross_margin: 68.0, gm_trend: -0.5, rev_growth_accel: 0.5,
    rule_of_40: 45,
    guru_cost: 195, guru_cost_type: '추정',
    guru_note: '버핏 소량 보유. Sridhar Ramaswamy CEO 취임 후 AI 전환 가속.',
    segments: [
      { name: '제품 매출(소비 기반)', pct: 92, growth: 29.0, trend: 'stable' },
      { name: '서비스', pct: 8, growth: 10.0, trend: 'stable' },
    ],
    key_risk: '소비 기반 모델로 경기 둔화 시 매출 변동성. SBC 과다.',
    key_oppty: 'Arctic AI/Cortex 플랫폼 전환. 데이터 클라우드 표준.',
    pe_hist_avg_5y: null,
  },

  UBER: {
    name: '우버', nameEn: 'Uber Technologies', flag: '🇺🇸',
    sector: '플랫폼·자율주행', type: 'watch',
    exchange: 'NYSE',
    fair_value: 98, fair_low: 62, fair_high: 140,
    eps_ttm: 1.52, revenue_ttm: 44.0e9,
    revenue_per_share: 20.8, bvps: 7.2,
    fcf_annual: 6.0e9, sbc_annual: 1.5e9,
    shares_out: 2.11e9, net_cash: 6.8e9,
    piotroski: 7, beneish_m: -1.9, altman_z: 3.2,
    roic: 18.5, wacc: 10.5,
    mom_12_1: 8.2, erv_score: 0.28,
    rev_growth_yoy: 18.0, gross_margin: 39.0, gm_trend: 1.5, rev_growth_accel: 1.2,
    rule_of_40: 40,
    guru_cost: 82, guru_cost_type: '역산 추정',
    guru_note: '비용구조 개선 + FCF 전환. Waymo 자율주행 파트너십 수혜.',
    segments: [
      { name: '모빌리티(라이드)', pct: 60, growth: 22.0, trend: 'accel' },
      { name: '배달(Eats)', pct: 35, growth: 14.0, trend: 'stable' },
      { name: '화물(Freight)', pct: 5, growth: 5.0, trend: 'stable' },
    ],
    key_risk: '자율주행 차량 확산 시 비즈니스모델 위협. 규제 리스크.',
    key_oppty: 'Waymo 파트너십. 광고 수익화. 자율주행 수수료 증가.',
    pe_hist_avg_5y: null,
  },

  ABNB: {
    name: '에어비앤비', nameEn: 'Airbnb Inc.', flag: '🇺🇸',
    sector: '여행 플랫폼', type: 'watch',
    exchange: 'NASDAQ',
    fair_value: 165, fair_low: 110, fair_high: 230,
    eps_ttm: 5.12, revenue_ttm: 11.1e9,
    revenue_per_share: 17.5, bvps: 4.5,
    fcf_annual: 4.5e9, sbc_annual: 0.8e9,
    shares_out: 0.637e9, net_cash: 10.8e9,
    piotroski: 7, beneish_m: -2.1, altman_z: 5.8,
    roic: 28.5, wacc: 9.5,
    mom_12_1: -8.4, erv_score: 0.08,
    rev_growth_yoy: 11.0, gross_margin: 83.0, gm_trend: 0.2, rev_growth_accel: -1.0,
    guru_cost: 145, guru_cost_type: '역산 추정',
    guru_note: '높은 FCF마진·자사주 매입. 여행 수요 정상화 우려.',
    segments: [
      { name: '호스트 수수료', pct: 100, growth: 11.0, trend: 'stable' },
    ],
    key_risk: '여행 소비 둔화. 경쟁(Vrbo·Hotels). 규제(NYC 단기임대 금지).',
    key_oppty: '체험 카테고리 확장. FCF Yield 8%+ 자사주 매입.',
    pe_hist_avg_5y: null,
  },

  SHOP: {
    name: '쇼피파이', nameEn: 'Shopify Inc.', flag: '🇨🇦',
    sector: '이커머스 플랫폼', type: 'watch',
    exchange: 'NYSE',
    fair_value: 115, fair_low: 72, fair_high: 165,
    eps_ttm: 0.54, revenue_ttm: 8.9e9,
    revenue_per_share: 6.92, bvps: 12.4,
    fcf_annual: 1.5e9, sbc_annual: 0.8e9,
    shares_out: 1.28e9, net_cash: 5.8e9,
    piotroski: 7, beneish_m: -2.0, altman_z: null,
    roic: 8.2, wacc: 11.0,
    mom_12_1: 15.2, erv_score: 0.32,
    rev_growth_yoy: 26.0, gross_margin: 51.0, gm_trend: 0.8, rev_growth_accel: 2.0,
    rule_of_40: 52,
    guru_cost: 98, guru_cost_type: '역산 추정',
    guru_note: '물류 매각 후 소프트웨어 마진 개선. B2B 파트너십 확장.',
    segments: [
      { name: 'Merchant Solutions', pct: 73, growth: 28.0, trend: 'accel' },
      { name: 'Subscription', pct: 27, growth: 22.0, trend: 'stable' },
    ],
    key_risk: '아마존 경쟁. 소비 둔화 시 SMB 이탈. 고PSR.',
    key_oppty: 'AI 커머스 도구. B2B 확장. Shop Pay GMV 성장.',
    pe_hist_avg_5y: null,
  },

  // ── 추가 트래킹 종목 ────────────────────────────
  NFLX: {
    name: '넷플릭스', nameEn: 'Netflix Inc.', flag: '🇺🇸',
    sector: '스트리밍·미디어', type: 'watch', exchange: 'NASDAQ',
    // 2025-11-17 10:1 액면분할 반영 완료
    fair_value: 120, fair_low: 95, fair_high: 145,
    eps_ttm: 2.48, revenue_ttm: 39.0e9,
    fcf_annual: 7.0e9, sbc_annual: 0.8e9,
    shares_out: 4.3e9, net_cash: 3.5e9,
    piotroski: 7, beneish_m: -2.3, altman_z: 5.1,
    roic: 22.0, wacc: 9.5,
    mom_12_1: 28.0, erv_score: 0.4,
    rev_growth_yoy: 16.0, rev_growth_accel: 1.5,
    gross_margin: 46.0, gm_trend: 2.5,
    rule_of_40: 62, tam_penetration: 12,
    guru_cost: 95, guru_cost_type: '역산 추정',
    guru_note: '광고 티어 + 라이브 스포츠로 2차 성장 국면',
    segments: [
      { name: '스트리밍 구독', pct: 88, growth: 16.0, trend: 'accel' },
      { name: '광고 티어', pct: 8, growth: 90.0, trend: 'accel' },
      { name: '기타', pct: 4, growth: 5.0, trend: 'stable' },
    ],
    key_risk: '콘텐츠 비용 증가. 광고 경기 민감. 구독자 포화.',
    key_oppty: '광고 플랫폼 고성장. 라이브 스포츠 중계권 확보.',
    pe_hist_avg_5y: 45.0, pe_hist_min_5y: 18.0, pe_hist_max_5y: 90.0,
  },

  NOW: {
    name: '서비스나우', nameEn: 'ServiceNow Inc.', flag: '🇺🇸',
    sector: 'AI 소프트웨어', type: 'watch', exchange: 'NYSE',
    // 2025-12-18 5:1 액면분할 반영 완료
    fair_value: 220, fair_low: 170, fair_high: 270,
    eps_ttm: 3.3, revenue_ttm: 10.9e9,
    fcf_annual: 3.5e9, sbc_annual: 0.9e9,
    shares_out: 1.05e9, net_cash: 1.8e9,
    piotroski: 7, beneish_m: -2.2, altman_z: 6.0,
    roic: 18.0, wacc: 10.0,
    mom_12_1: 22.0, erv_score: 0.35,
    rev_growth_yoy: 22.0, rev_growth_accel: 1.0,
    gross_margin: 79.0, gm_trend: 0.5,
    rule_of_40: 101, tam_penetration: 4,
    guru_cost: 176, guru_cost_type: '역산 추정',
    guru_note: '엔터프라이즈 AI 자동화 선도. 이탈률 <2%.',
    segments: [
      { name: 'ITSM·클라우드', pct: 75, growth: 22.0, trend: 'stable' },
      { name: 'AI Agents', pct: 15, growth: 80.0, trend: 'accel' },
      { name: '기타 SaaS', pct: 10, growth: 18.0, trend: 'stable' },
    ],
    key_risk: '높은 밸류에이션. 경기 침체 시 IT예산 삭감.',
    key_oppty: 'Agentic AI 자동화 전면 도입. 정부·금융 클라우드 전환.',
    pe_hist_avg_5y: 60.0, pe_hist_min_5y: 35.0, pe_hist_max_5y: 120.0,
  },

  ADBE: {
    name: '어도비', nameEn: 'Adobe Inc.', flag: '🇺🇸',
    sector: 'AI 소프트웨어', type: 'watch', exchange: 'NASDAQ',
    fair_value: 520, fair_low: 400, fair_high: 650,
    eps_ttm: 18.5, revenue_ttm: 21.5e9,
    fcf_annual: 8.0e9, sbc_annual: 1.0e9,
    shares_out: 0.44e9, net_cash: 2.0e9,
    piotroski: 8, beneish_m: -2.4, altman_z: 7.5,
    roic: 35.0, wacc: 9.0,
    mom_12_1: 5.0, erv_score: 0.1,
    rev_growth_yoy: 11.0, rev_growth_accel: -1.0,
    gross_margin: 88.0, gm_trend: 0.2,
    rule_of_40: 99, tam_penetration: 18,
    guru_cost: 450, guru_cost_type: '역산 추정',
    guru_note: 'Firefly AI 상용화. 크리에이티브 클라우드 방어력.',
    segments: [
      { name: '크리에이티브 클라우드', pct: 58, growth: 10.0, trend: 'stable' },
      { name: 'Document Cloud', pct: 22, growth: 14.0, trend: 'stable' },
      { name: 'DX Cloud', pct: 20, growth: 12.0, trend: 'stable' },
    ],
    key_risk: 'AI 경쟁(Canva, Midjourney). 성장 둔화. Figma 인수 불발.',
    key_oppty: 'Firefly AI 수익화. GenAI 크리에이티브 플랫폼 확장.',
    pe_hist_avg_5y: 50.0, pe_hist_min_5y: 25.0, pe_hist_max_5y: 78.0,
  },

  CRM: {
    name: '세일즈포스', nameEn: 'Salesforce Inc.', flag: '🇺🇸',
    sector: 'AI 소프트웨어', type: 'watch', exchange: 'NYSE',
    fair_value: 320, fair_low: 240, fair_high: 400,
    eps_ttm: 10.5, revenue_ttm: 37.9e9,
    fcf_annual: 12.0e9, sbc_annual: 2.5e9,
    shares_out: 0.96e9, net_cash: 2.5e9,
    piotroski: 7, beneish_m: -2.0, altman_z: 4.8,
    roic: 14.0, wacc: 9.5,
    mom_12_1: 8.0, erv_score: 0.2,
    rev_growth_yoy: 9.0, rev_growth_accel: 0.5,
    gross_margin: 77.0, gm_trend: 1.0,
    rule_of_40: 86, tam_penetration: 20,
    guru_cost: 270, guru_cost_type: '역산 추정',
    guru_note: 'Agentforce AI 에이전트. 대형 엔터프라이즈 방어력.',
    segments: [
      { name: 'Sales Cloud', pct: 32, growth: 8.0, trend: 'stable' },
      { name: 'Service Cloud', pct: 28, growth: 10.0, trend: 'stable' },
      { name: 'AI·Data Cloud', pct: 20, growth: 40.0, trend: 'accel' },
      { name: '기타', pct: 20, growth: 7.0, trend: 'stable' },
    ],
    key_risk: '성장 둔화. 높은 SBC. 경쟁 심화(MS, SAP).',
    key_oppty: 'Agentforce AI 에이전트 수익화. Data Cloud 확장.',
    pe_hist_avg_5y: 55.0, pe_hist_min_5y: 30.0, pe_hist_max_5y: 100.0,
  },

  PANW: {
    name: '팔로알토', nameEn: 'Palo Alto Networks', flag: '🇺🇸',
    sector: '사이버보안 AI', type: 'watch', exchange: 'NASDAQ',
    fair_value: 220, fair_low: 165, fair_high: 275,
    eps_ttm: 6.0, revenue_ttm: 8.7e9,
    fcf_annual: 3.5e9, sbc_annual: 0.8e9,
    shares_out: 1.34e9, net_cash: 2.8e9,
    piotroski: 6, beneish_m: -1.9, altman_z: 3.5,
    roic: 12.0, wacc: 10.0,
    mom_12_1: 15.0, erv_score: 0.25,
    rev_growth_yoy: 14.0, rev_growth_accel: 0.5,
    gross_margin: 75.0, gm_trend: 0.8,
    rule_of_40: 89, tam_penetration: 5,
    guru_cost: 170, guru_cost_type: '역산 추정',
    guru_note: 'AI보안 플랫폼화. "Platformization" 전략 효과.',
    segments: [
      { name: '보안 플랫폼', pct: 60, growth: 18.0, trend: 'accel' },
      { name: 'NGS ARR', pct: 30, growth: 30.0, trend: 'accel' },
      { name: '기타', pct: 10, growth: 5.0, trend: 'stable' },
    ],
    key_risk: '무료 제공(platformization) 단기 수익 압박.',
    key_oppty: 'AI-native 보안. 고객당 매출 확대(upsell).',
    pe_hist_avg_5y: 55.0, pe_hist_min_5y: 30.0, pe_hist_max_5y: 100.0,
  },

  APP: {
    name: '앱러빈', nameEn: 'AppLovin Corp.', flag: '🇺🇸',
    sector: 'AI 광고·모바일', type: 'watch', exchange: 'NASDAQ',
    fair_value: 380, fair_low: 250, fair_high: 500,
    eps_ttm: 8.0, revenue_ttm: 5.1e9,
    fcf_annual: 2.8e9, sbc_annual: 0.4e9,
    shares_out: 0.34e9, net_cash: -2.5e9,
    piotroski: 7, beneish_m: -2.1, altman_z: 3.8,
    roic: 45.0, wacc: 12.0,
    mom_12_1: 85.0, erv_score: 0.6,
    rev_growth_yoy: 75.0, rev_growth_accel: 8.0,
    gross_margin: 75.0, gm_trend: 5.0,
    rule_of_40: 150, tam_penetration: 2,
    guru_cost: 200, guru_cost_type: '역산 추정',
    guru_note: 'AXON AI 광고엔진. 모바일게임 인앱광고 최강자.',
    segments: [
      { name: 'Software(AXON AI)', pct: 65, growth: 100.0, trend: 'accel' },
      { name: '앱 포트폴리오', pct: 35, growth: 5.0, trend: 'stable' },
    ],
    key_risk: '고밸류. AI 광고 경쟁(Meta, Google). 모바일 광고 경기 민감.',
    key_oppty: 'AXON AI 전환율 혁명. e-커머스 광고로 TAM 확장.',
    pe_hist_avg_5y: null, pe_hist_min_5y: null, pe_hist_max_5y: null,
  },

  MDB: {
    name: '몽고DB', nameEn: 'MongoDB Inc.', flag: '🇺🇸',
    sector: '클라우드 DB', type: 'watch', exchange: 'NASDAQ',
    fair_value: 280, fair_low: 200, fair_high: 380,
    eps_ttm: -2.0, revenue_ttm: 2.1e9,
    fcf_annual: 0.4e9, sbc_annual: 0.35e9,
    shares_out: 0.25e9, net_cash: 1.5e9,
    piotroski: 5, beneish_m: -2.1, altman_z: 4.2,
    roic: 5.0, wacc: 10.5,
    mom_12_1: -15.0, erv_score: -0.1,
    rev_growth_yoy: 22.0, rev_growth_accel: -2.0,
    gross_margin: 70.0, gm_trend: 0.5,
    rule_of_40: 92, tam_penetration: 3,
    guru_cost: 350, guru_cost_type: '역산 추정',
    guru_note: '비정형 데이터 DB 1위. Atlas AI 워크로드 확장.',
    segments: [
      { name: 'Atlas (클라우드)', pct: 68, growth: 30.0, trend: 'accel' },
      { name: 'Enterprise Advanced', pct: 32, growth: 10.0, trend: 'stable' },
    ],
    key_risk: '가이던스 보수적. DBA 씩씩하게 줄어드는 수요.',
    key_oppty: 'AI 애플리케이션 벡터DB. Atlas SQL 확장.',
    pe_hist_avg_5y: null, pe_hist_min_5y: null, pe_hist_max_5y: null,
  },

  DDOG: {
    name: '데이터독', nameEn: 'Datadog Inc.', flag: '🇺🇸',
    sector: '클라우드 모니터링', type: 'watch', exchange: 'NASDAQ',
    fair_value: 175, fair_low: 125, fair_high: 230,
    eps_ttm: 1.8, revenue_ttm: 2.68e9,
    fcf_annual: 0.8e9, sbc_annual: 0.45e9,
    shares_out: 0.34e9, net_cash: 2.8e9,
    piotroski: 7, beneish_m: -2.2, altman_z: 5.5,
    roic: 15.0, wacc: 10.0,
    mom_12_1: 12.0, erv_score: 0.3,
    rev_growth_yoy: 26.0, rev_growth_accel: 2.0,
    gross_margin: 81.0, gm_trend: 0.8,
    rule_of_40: 107, tam_penetration: 4,
    guru_cost: 130, guru_cost_type: '역산 추정',
    guru_note: 'AI 인프라 모니터링 1위. GPU 클러스터 관측 수요.',
    segments: [
      { name: '인프라 모니터링', pct: 50, growth: 20.0, trend: 'stable' },
      { name: 'APM·보안·AI', pct: 50, growth: 32.0, trend: 'accel' },
    ],
    key_risk: '클라우드 최적화 압박. Grafana 오픈소스 경쟁.',
    key_oppty: 'AI 모델 모니터링. LLM observability 신시장.',
    pe_hist_avg_5y: null, pe_hist_min_5y: null, pe_hist_max_5y: null,
  },

  ZS: {
    name: '지스케일러', nameEn: 'Zscaler Inc.', flag: '🇺🇸',
    sector: '사이버보안 AI', type: 'watch', exchange: 'NASDAQ',
    fair_value: 260, fair_low: 190, fair_high: 330,
    eps_ttm: 1.0, revenue_ttm: 2.5e9,
    fcf_annual: 0.9e9, sbc_annual: 0.55e9,
    shares_out: 0.155e9, net_cash: 2.6e9,
    piotroski: 6, beneish_m: -2.0, altman_z: 4.0,
    roic: 10.0, wacc: 11.0,
    mom_12_1: 10.0, erv_score: 0.2,
    rev_growth_yoy: 21.0, rev_growth_accel: 0.0,
    gross_margin: 79.0, gm_trend: 0.5,
    rule_of_40: 100, tam_penetration: 3,
    guru_cost: 200, guru_cost_type: '역산 추정',
    guru_note: 'Zero Trust 보안 선구자. 정부·대기업 채택 확대.',
    segments: [
      { name: 'ZIA (인터넷접근)', pct: 55, growth: 18.0, trend: 'stable' },
      { name: 'ZPA (프라이빗접근)', pct: 35, growth: 28.0, trend: 'accel' },
      { name: 'ZDX·기타', pct: 10, growth: 35.0, trend: 'accel' },
    ],
    key_risk: 'Palo Alto 플랫폼화 경쟁. 성장 둔화 우려.',
    key_oppty: 'AI 보안 데이터 레이크. Zero Trust 전면 전환.',
    pe_hist_avg_5y: null, pe_hist_min_5y: null, pe_hist_max_5y: null,
  },

  MELI: {
    name: '메르카도리브레', nameEn: 'MercadoLibre Inc.', flag: '🇧🇷',
    sector: '이커머스·핀테크', type: 'watch', exchange: 'NASDAQ',
    fair_value: 2800, fair_low: 2100, fair_high: 3500,
    eps_ttm: 42.0, revenue_ttm: 21.0e9,
    fcf_annual: 2.5e9, sbc_annual: 0.5e9,
    shares_out: 0.05e9, net_cash: 3.0e9,
    piotroski: 7, beneish_m: -2.2, altman_z: 4.5,
    roic: 22.0, wacc: 12.0,
    mom_12_1: 30.0, erv_score: 0.4,
    rev_growth_yoy: 35.0, rev_growth_accel: 2.0,
    gross_margin: 54.0, gm_trend: 1.5,
    rule_of_40: 89, tam_penetration: 6,
    guru_cost: 1800, guru_cost_type: '역산 추정',
    guru_note: '남미 아마존+페이팔. Mercado Pago 핀테크 고성장.',
    segments: [
      { name: 'Commerce', pct: 55, growth: 30.0, trend: 'accel' },
      { name: 'Fintech (Pago)', pct: 40, growth: 42.0, trend: 'accel' },
      { name: '광고·기타', pct: 5, growth: 55.0, trend: 'accel' },
    ],
    key_risk: '남미 환율 리스크. 현지 규제. 인플레이션.',
    key_oppty: '남미 금융 미포함 인구 대상 핀테크. 물류 네트워크 확장.',
    pe_hist_avg_5y: 65.0, pe_hist_min_5y: 35.0, pe_hist_max_5y: 120.0,
  },

  BKNG: {
    name: '부킹홀딩스', nameEn: 'Booking Holdings', flag: '🇺🇸',
    sector: '온라인 여행', type: 'watch', exchange: 'NASDAQ',
    // 2026-04-06 25:1 액면분할 반영 완료
    fair_value: 232, fair_low: 180, fair_high: 288,
    eps_ttm: 8.4, revenue_ttm: 23.5e9,
    fcf_annual: 7.5e9, sbc_annual: 0.5e9,
    shares_out: 0.95e9, net_cash: 3.5e9,
    piotroski: 8, beneish_m: -2.5, altman_z: 6.5,
    roic: 42.0, wacc: 9.0,
    mom_12_1: 20.0, erv_score: 0.3,
    rev_growth_yoy: 12.0, rev_growth_accel: 0.5,
    gross_margin: 82.0, gm_trend: 0.5,
    rule_of_40: 94, tam_penetration: 8,
    guru_cost: 168, guru_cost_type: '역산 추정',
    guru_note: '유럽 여행 독점. AI여행 어시스턴트. FCF 수익률 최상위.',
    segments: [
      { name: '숙박 예약', pct: 78, growth: 12.0, trend: 'stable' },
      { name: '항공·렌터카', pct: 15, growth: 18.0, trend: 'accel' },
      { name: 'Attract·기타', pct: 7, growth: 25.0, trend: 'accel' },
    ],
    key_risk: '경기 침체 시 여행 수요 급감. 구글 여행 직접 경쟁.',
    key_oppty: 'AI 여행 어시스턴트. 아시아 확장. 자사주 매입 지속.',
    pe_hist_avg_5y: 22.0, pe_hist_min_5y: 12.0, pe_hist_max_5y: 38.0,
  },

  QCOM: {
    name: '퀄컴', nameEn: 'Qualcomm Inc.', flag: '🇺🇸',
    sector: 'AI 반도체', type: 'watch', exchange: 'NASDAQ',
    fair_value: 200, fair_low: 155, fair_high: 260,
    eps_ttm: 10.5, revenue_ttm: 39.0e9,
    fcf_annual: 10.0e9, sbc_annual: 1.2e9,
    shares_out: 0.84e9, net_cash: 4.5e9,
    piotroski: 7, beneish_m: -2.3, altman_z: 5.5,
    roic: 30.0, wacc: 10.0,
    mom_12_1: 5.0, erv_score: 0.2,
    rev_growth_yoy: 15.0, rev_growth_accel: 1.0,
    gross_margin: 57.0, gm_trend: 1.0,
    rule_of_40: 72, tam_penetration: 20,
    guru_cost: 160, guru_cost_type: '역산 추정',
    guru_note: 'AI PC 스냅드래곤X. 자동차 칩 다각화. Apple 탈QC 리스크.',
    segments: [
      { name: 'QCT 스마트폰', pct: 65, growth: 12.0, trend: 'stable' },
      { name: 'QCT IoT·자동차', pct: 20, growth: 35.0, trend: 'accel' },
      { name: 'QTL 라이선스', pct: 15, growth: 8.0, trend: 'stable' },
    ],
    key_risk: 'Apple 자체 칩 전환. 중국 판매 비중 높음.',
    key_oppty: 'On-device AI PC/모바일. 자동차 칩 $45B TAM.',
    pe_hist_avg_5y: 16.0, pe_hist_min_5y: 10.0, pe_hist_max_5y: 28.0,
  },

  ANET: {
    name: '아리스타 네트웍스', nameEn: 'Arista Networks', flag: '🇺🇸',
    sector: 'AI 네트워크 인프라', type: 'watch', exchange: 'NYSE',
    fair_value: 120, fair_low: 88, fair_high: 155,
    eps_ttm: 2.6, revenue_ttm: 7.7e9,
    fcf_annual: 2.8e9, sbc_annual: 0.35e9,
    shares_out: 0.315e9, net_cash: 6.5e9,
    piotroski: 9, beneish_m: -2.8, altman_z: 9.0,
    roic: 38.0, wacc: 9.5,
    mom_12_1: 40.0, erv_score: 0.5,
    rev_growth_yoy: 28.0, rev_growth_accel: 3.0,
    gross_margin: 65.0, gm_trend: 0.5,
    rule_of_40: 93, tam_penetration: 7,
    guru_cost: 85, guru_cost_type: '역산 추정',
    guru_note: 'AI 클러스터 이더넷 스위치. Meta·MS·Google 핵심 공급사.',
    segments: [
      { name: '데이터센터 스위치', pct: 85, growth: 30.0, trend: 'accel' },
      { name: 'Campus·엣지', pct: 15, growth: 15.0, trend: 'stable' },
    ],
    key_risk: '인피니밴드(Nvidia) 경쟁. 클라우드 CapEx 사이클 민감.',
    key_oppty: 'AI 클러스터 네트워킹 표준화. EOS 소프트웨어 구독 확대.',
    pe_hist_avg_5y: 38.0, pe_hist_min_5y: 22.0, pe_hist_max_5y: 65.0,
  },

  CELH: {
    name: '셀시우스', nameEn: 'Celsius Holdings', flag: '🇺🇸',
    sector: '에너지드링크·소비재', type: 'watch', exchange: 'NASDAQ',
    fair_value: 55, fair_low: 35, fair_high: 80,
    eps_ttm: 0.6, revenue_ttm: 1.45e9,
    fcf_annual: 0.2e9, sbc_annual: 0.06e9,
    shares_out: 0.25e9, net_cash: 0.8e9,
    piotroski: 6, beneish_m: -2.0, altman_z: 4.0,
    roic: 18.0, wacc: 11.0,
    mom_12_1: -25.0, erv_score: -0.3,
    rev_growth_yoy: -5.0, rev_growth_accel: -8.0,
    gross_margin: 50.0, gm_trend: -1.5,
    rule_of_40: 45, tam_penetration: 4,
    guru_cost: 70, guru_cost_type: '역산 추정',
    guru_note: 'Pepsi 유통망. 성장 둔화 후 재가속 여부가 핵심.',
    segments: [
      { name: '북미 에너지드링크', pct: 85, growth: -8.0, trend: 'down' },
      { name: '해외', pct: 15, growth: 25.0, trend: 'accel' },
    ],
    key_risk: '수요 정체. Monster·Red Bull 역습. 유통 집중도 위험.',
    key_oppty: '유럽·아시아 국제 확장. 건강음료 트렌드 수혜.',
    pe_hist_avg_5y: null, pe_hist_min_5y: null, pe_hist_max_5y: null,
  },
};

// ── 구루 포지션 (Q1 2026 13F 기준) ──────────────
// posture: 직전 분기 대비 순매수 규모·신규편입 비중을 근거로 판정한 공격성
export const GURU_POSITIONS = [
  {
    id: 'ackman', name: '빌 애크먼', fund: 'Pershing Square', tier: 1,
    updated: '2026 Q1', aum_b: 18.5,
    posture: '공격적 매수', posture_score: 82,
    qoq_summary: '전분기 대비 상위 3종목 합산 비중 44.0%→44.0%. MSFT 신규 15.3% 대형 진입 + AMZN 19% 순증. 현금 비중 축소, 자산배분 상위 3종목에 재집중.',
    positions: [
      { sym: 'MSFT', action: 'NEW', shares: '565만주', weight_pct: 15.26,
        cost_est: 435.22, cost_type: '확인값',
        note: '21배 선행PER 진입, 지금 8.8% 저렴' },
      { sym: 'AMZN', action: 'ADD', shares: '1,145만주 (+19%)', weight_pct: 17.39,
        cost_est: 209, cost_type: '역산 추정',
        note: '애크먼+테퍼 동시 매수, 현재 30% 비쌈' },
      { sym: 'META', action: 'HOLD', shares: '266만주', weight_pct: 11.37,
        cost_est: 650, cost_type: '역산 추정',
        note: '현재 $570으로 애크먼보다 12% 저렴' },
    ],
  },
  {
    id: 'druckenmiller', name: '드러켄밀러', fund: 'Duquesne Family Office', tier: 2,
    updated: '2026 Q1', aum_b: 3.38,
    posture: '선별적 재조정', posture_score: 48,
    qoq_summary: 'GOOGL 전량 매도(비중 0%)로 매크로 리스크 회피, 대신 AVGO 신규 소규모(3.5%) 진입. NTRA 4년 초장기 보유는 유지 — 종목별 확신 차등화가 뚜렷한 분기.',
    positions: [
      { sym: 'NTRA', action: 'HOLD', shares: '340만주', weight_pct: 18.1,
        cost_est: 86, cost_type: '역산 추정(4년)',
        note: '4년 보유 +126%. 최강 신뢰 신호.' },
      { sym: 'AVGO', action: 'NEW', shares: '195,955주', weight_pct: 3.5,
        cost_est: 310, cost_type: '역산 추정',
        note: 'Q1 신규 $310 매수, 현재 $388 = +25%' },
      { sym: 'GOOGL', action: 'SOLD', shares: '전량 매도', weight_pct: 0,
        cost_est: 397, cost_type: '역산 추정(매도가)',
        note: '단기 매크로 관점 이탈. 버크셔는 반대로 매수.' },
    ],
  },
  {
    id: 'berkshire', name: '워런 버핏(아벨)', fund: 'Berkshire Hathaway', tier: 1,
    updated: '2026 Q1', aum_b: 342,
    posture: '중립~점진적 진입', posture_score: 55,
    qoq_summary: 'AAPL 비중 서서히 축소(21.99%, 다분기 연속 감소 추세) — 차익실현·집중도 완화 목적. 반면 그렉 아벨 체제 첫 빅테크 신규 베팅으로 GOOGL $100억 편입. 초대형 포트폴리오 특성상 회전율은 낮지만 방향은 "빅테크 재분산".',
    positions: [
      { sym: 'AAPL', action: 'REDUCE', shares: '3.0억주 (축소 중)', weight_pct: 21.99,
        cost_est: 165, cost_type: '역산 추정',
        note: '비중 서서히 축소. 보험 목적 보유 지속.' },
      { sym: 'GOOGL', action: 'NEW', shares: '6월 $100억 신규', weight_pct: null,
        cost_est: 390, cost_type: '역산 추정',
        note: '그렉 아벨 첫 빅테크 베팅. 현재 $356으로 저렴.' },
    ],
  },
  {
    id: 'tepper', name: '데이비드 테퍼', fund: 'Appaloosa Mgmt', tier: 2,
    updated: '2026 Q1', aum_b: 14.2,
    posture: '공격적 매수', posture_score: 88,
    qoq_summary: 'AMZN 비중 98% 순증 — 올 분기 최대 매수 폭. 애크먼과 동일 가격대 동시 매수로 "슈퍼투자자 클러스터" 형성, 신뢰도 높은 신호로 해석. META는 비중 유지하며 확신 구간 지속.',
    positions: [
      { sym: 'AMZN', action: 'ADD', shares: '430만주 (+98%)', weight_pct: 15.2,
        cost_est: 209, cost_type: '역산 추정',
        note: '애크먼과 동시 동일 가격 매수. 강한 클러스터.' },
      { sym: 'META', action: 'HOLD', shares: '180만주', weight_pct: 9.8,
        cost_est: 580, cost_type: '역산 추정',
        note: '현재 $570으로 테퍼 매수가 근처.' },
    ],
  },
];

// ── 매크로 설정 (FRED로 자동, 아래는 초기값) ─────
export const MACRO_INIT = {
  fed_rate: 3.75,
  treasury_10y: 4.42,
  sp500: 7420,
  sp500_dcf_fair: 7180,
  shiller_cape: 37,
  buffett_indicator: 196,
  ism_pmi: 48.9,
  dxy: 105,
  usd_krw: 1384,
  cpi_yoy: 3.1,
  regime: '후기사이클',
  regime_detail: '금리 고점 유지 + AI 섹터 강세',
  stock_cash_ratio: 60,
  updated: '2026-06-27',
};

// ── 매크로 지표 설명 메타데이터 ───────────────────
// 각 지표: 정의(what) · 왜 중요한지(why) · 현재값 해석 구간(levels) · 역사적 사례(history)
// score: 0~100 환산 (100=매우 우호적, 0=매우 위험)
export const MACRO_META = {
  fed_rate: {
    label: 'Fed 기준금리', short: 'Fed금리', unit: '%', icon: '🏦',
    what: '연준(Fed)이 은행 간 초단기 자금 대출에 적용하는 목표금리. 모든 대출·채권·주식 할인율의 출발점입니다.',
    why: '금리가 오르면 기업의 대출이자 부담이 커지고, 미래 이익을 현재가치로 환산할 때 할인폭이 커져 특히 "먼 미래의 이익"에 의존하는 성장주·고PER 종목의 주가가 눌립니다. 금리가 낮으면 반대로 위험자산에 우호적입니다.',
    benchmark: '중립금리(경기를 부양하지도 억제하지도 않는 수준) 약 2.5%',
    levels: [
      { max: 2.0, label: '완화적', color: 'green', desc: '경기부양 국면. 위험자산(성장주)에 강하게 우호적.' },
      { max: 4.0, label: '중립', color: 'gold', desc: '방향성 뚜렷하지 않음. 개별 종목 펀더멘털이 더 중요.' },
      { max: 99, label: '긴축적', color: 'red', desc: '고금리 장기화 국면. 밸류에이션 압박, 특히 무이익 성장주에 불리.' },
    ],
    history: '2022~2023년 Fed가 0%→5.25%로 급격히 인상하자 나스닥은 고점 대비 -33% 조정. 반대로 2020년 제로금리 시기엔 성장주가 사상 최대 랠리를 기록했습니다.',
    scoreFn: v => v == null ? 50 : v > 5 ? 10 : v > 4 ? 30 : v > 2.5 ? 55 : v > 1 ? 80 : 95,
  },
  shiller_cape: {
    label: 'Shiller CAPE', short: 'CAPE', unit: 'x', icon: '📐',
    what: '노벨경제학상 수상자 로버트 실러가 만든 지표로, S&P500 주가를 "물가조정 후 최근 10년 평균 이익"으로 나눈 값. 일반 PER보다 경기순환의 영향을 덜 받아 장기 고평가/저평가 판단에 씁니다.',
    why: 'CAPE가 역사 평균보다 높을수록 "향후 10년 기대수익률"이 통계적으로 낮아지는 경향이 있습니다. 반드시 단기 폭락을 의미하진 않지만, 장기 기대수익률의 나침반 역할을 합니다.',
    benchmark: '20세기 이후 장기 평균 약 17배',
    levels: [
      { max: 20, label: '저평가~적정', color: 'green', desc: '역사 평균 이하. 장기 기대수익률 양호.' },
      { max: 30, label: '다소 고평가', color: 'gold', desc: '평균 상회. 향후 수익률 둔화 가능성.' },
      { max: 99, label: '고평가', color: 'red', desc: '역사적 상위권. 닷컴버블(1999년 44배) 근접 시 각별 주의.' },
    ],
    history: '1999년 닷컴버블 정점 44배에서 2000~2002년 나스닥 -78% 폭락. 2007년 27배에서 금융위기 -57%. 다만 2010년대 내내 25~30배에서도 장기 상승장이 지속된 사례도 있어 "타이밍 지표"가 아닌 "리스크 게이지"로 활용해야 합니다.',
    scoreFn: v => v == null ? 50 : v > 35 ? 10 : v > 28 ? 30 : v > 22 ? 55 : v > 17 ? 75 : 90,
  },
  buffett_indicator: {
    label: '버핏 지수', short: '버핏지수', unit: '%', icon: '📊',
    what: '워런 버핏이 "가장 좋은 단일 밸류에이션 척도"라 부른 지표. 미국 전체 상장주식 시가총액을 GDP(국내총생산)로 나눈 값입니다.',
    why: '실물경제 규모 대비 주식시장이 얼마나 부풀었는지 보여줍니다. 100%를 넘으면 주식시장이 경제 생산능력보다 빠르게 커졌다는 뜻으로, 장기적으로 평균회귀 압력이 존재합니다.',
    benchmark: '역사 평균 약 80~100%, 경고 구간 140%+',
    levels: [
      { max: 100, label: '저평가', color: 'green', desc: '경제 규모 대비 시장이 작음. 매수 우호적 구간.' },
      { max: 140, label: '적정~다소 고평가', color: 'gold', desc: '평균 상회. 선별적 접근 필요.' },
      { max: 999, label: '고평가', color: 'red', desc: '역사적 극단 구간. 2000년 닷컴버블(약 140%), 지금은 그보다 높은 수준.' },
    ],
    history: '2000년 닷컴버블 정점 약 140%에서 이후 2년간 대형 조정. 2021년 말 약 200%대에서 2022년 나스닥 -33% 조정. 단, 저금리·플랫폼 기업 마진구조 변화로 "적정 레벨" 자체가 과거보다 높아졌다는 반론도 있습니다.',
    scoreFn: v => v == null ? 50 : v > 180 ? 10 : v > 150 ? 25 : v > 120 ? 50 : v > 100 ? 70 : 90,
  },
  ism_pmi: {
    label: 'ISM 제조업 PMI', short: 'ISM PMI', unit: '', icon: '🏭',
    what: '미국 공급관리협회(ISM)가 매달 제조업 구매관리자들을 설문해 만드는 경기 체감지수. 50을 기준선으로 위면 확장, 아래면 수축을 의미합니다.',
    why: '제조업은 경기 사이클에 가장 먼저 반응하는 선행지표 성격이 강합니다. 50 미만이 지속되면 기업 실적 둔화 → 주가 조정으로 이어지는 경우가 많습니다.',
    benchmark: '기준선 50.0 (48.9면 "기준선보다 낮다" = 경기 수축 신호)',
    levels: [
      { max: 47, label: '뚜렷한 수축', color: 'red', desc: '제조업 경기 위축 뚜렷. 경기침체 경고음.' },
      { max: 50, label: '경미한 수축', color: 'gold', desc: '기준선 하회. 경기 둔화 초기 신호, 주의 필요.' },
      { max: 999, label: '확장', color: 'green', desc: '50 이상. 경기 확장 국면, 기업이익에 우호적.' },
    ],
    history: '2008년 금융위기 직전 PMI가 50 아래로 떨어진 뒤 급락. 2020년 코로나 초기 41.5까지 급락 후 V자 반등. 48.9는 "완만한 수축" 단계로, 즉각적 침체보다는 성장 모멘텀 둔화로 해석하는 것이 일반적입니다.',
    scoreFn: v => v == null ? 50 : v > 55 ? 90 : v > 52 ? 75 : v > 50 ? 60 : v > 47 ? 35 : 15,
  },
  cpi_yoy: {
    label: 'CPI (소비자물가, 전년비)', short: 'CPI', unit: '%', icon: '🛒',
    what: '전년 동월 대비 소비자물가 상승률. 인플레이션의 대표 지표입니다.',
    why: 'Fed의 물가 목표는 2%. CPI가 목표보다 높으면 Fed가 금리를 내리기 어려워지고, 고금리가 장기화되며 주식시장에 부담을 줍니다.',
    benchmark: 'Fed 목표치 2%',
    levels: [
      { max: 2.5, label: '안정권', color: 'green', desc: '목표 근접. 금리인하 여력 확보.' },
      { max: 3.5, label: '다소 높음', color: 'gold', desc: '목표 상회. 인하 속도 제한적.' },
      { max: 999, label: '높음', color: 'red', desc: '인플레 압력 지속. 추가 긴축 리스크.' },
    ],
    history: '2022년 CPI 9.1%까지 급등 시 Fed의 공격적 금리인상 촉발, 나스닥 -33%. 인플레이션 둔화 확인 전까지는 금리인하 기대가 계속 지연되는 경향이 있습니다.',
    scoreFn: v => v == null ? 50 : v > 4.5 ? 15 : v > 3.5 ? 35 : v > 2.5 ? 60 : v > 1.5 ? 85 : 70,
  },
  dxy: {
    label: '달러 인덱스(DXY)', short: 'DXY', unit: '', icon: '💵',
    what: '주요 6개국 통화 대비 달러 가치를 나타내는 지수.',
    why: '달러가 강세이면 해외 매출 비중이 큰 미국 기업의 실적이 환산 과정에서 깎이고(환차손), 신흥국 자금 유출 압력도 커집니다.',
    benchmark: '100 안팎이 중립, 103 이상이면 강달러 국면',
    levels: [
      { max: 100, label: '약달러', color: 'green', desc: '해외 매출 기업에 우호적.' },
      { max: 103, label: '중립', color: 'gold', desc: '특별한 방향성 없음.' },
      { max: 999, label: '강달러', color: 'red', desc: '해외 매출 비중 높은 기업 실적 역풍.' },
    ],
    history: '2022년 강달러(DXY 114) 국면에서 애플·마이크로소프트 등 해외매출 비중 높은 기업들이 실적 가이던스에서 환율 역풍을 명시적으로 언급.',
    scoreFn: v => v == null ? 50 : v > 108 ? 25 : v > 103 ? 45 : v > 98 ? 65 : 80,
  },
  fed_model: {
    label: 'Fed Model (주식 프리미엄)', short: 'Fed모델', unit: '%p', icon: '⚖️',
    what: '주식의 기대수익률(이익수익률 EY = 1/PER)에서 10년 국채금리를 뺀 값. 주식과 채권 중 상대적으로 어느 쪽이 매력적인지 비교하는 지표입니다.',
    why: '프리미엄이 낮거나 마이너스면 "위험을 감수하고 주식을 살 이유"가 줄어듭니다. 국채가 무위험으로 비슷한 수익을 주기 때문입니다.',
    benchmark: '역사적으로 +2%p 이상이면 주식이 매력적, 0 미만이면 채권 대비 매력 상실',
    levels: [
      { max: 0, label: '주식 매력 낮음', color: 'red', desc: '국채 대비 프리미엄 없음. 상대적으로 채권이 유리.' },
      { max: 1.5, label: '중립', color: 'gold', desc: '소폭 프리미엄. 선별적 접근.' },
      { max: 999, label: '주식 매력 높음', color: 'green', desc: '충분한 위험 프리미엄 확보.' },
    ],
    history: '2000년 닷컴버블 당시 Fed Model 프리미엄이 마이너스로 전환된 후 시장이 붕괴. 현재처럼 국채금리(4%대)가 높으면 프리미엄이 압박받는 구조입니다.',
    scoreFn: v => v == null ? 50 : v < -1 ? 10 : v < 0 ? 25 : v < 1 ? 50 : v < 2.5 ? 75 : 90,
  },
};

// ── 종목 지표 설명 메타데이터 (종목 상세 화면용) ──
export const METRIC_META = {
  piotroski: {
    label: 'Piotroski F-Score', icon: '🧮',
    what: '재무제표 9개 항목(수익성·재무구조·효율성)을 채점해 0~9점으로 만든 재무건전성 점수. 낮은 PBR 종목 중 "진짜 우량주"를 걸러내기 위해 고안됐습니다.',
    why: '학술 연구(Piotroski 2000)에서 F-Score 상위 종목이 하위 종목 대비 연 +7.5%p 초과수익을 낸 것으로 확인됐습니다. 회계 조작이 어려운 실질 지표라 신뢰도가 높습니다.',
    levels: [
      { min: 7, label: '우수', color: 'green', desc: '재무건전성 상위권. 안정적 성장 가능성.' },
      { min: 4, label: '보통', color: 'gold', desc: '평범한 수준. 다른 지표와 함께 판단 필요.' },
      { min: 0, label: '주의', color: 'red', desc: '재무구조 취약 가능성. 신중한 접근 필요.' },
    ],
  },
  beneish_m: {
    label: 'Beneish M-Score', icon: '🕵️',
    what: '매출채권·매출총이익률·자산의 질 등 8개 변수로 회계 조작(분식회계) 가능성을 탐지하는 점수.',
    why: '엔론 사태를 사전에 잡아낸 것으로 유명한 지표입니다. -1.78보다 크면(즉 -1.78에 가까워지면) 실적 조작 의심 신호로, 다른 지표가 아무리 좋아도 투자를 재검토해야 합니다.',
    levels: [
      { max: -2.5, label: '매우 안전', color: 'green', desc: '조작 가능성 낮음.' },
      { max: -1.78, label: '안전', color: 'green', desc: '통상적인 안전 범위 내.' },
      { max: 999, label: '조작 의심', color: 'red', desc: '⛔ -1.78 초과. 회계 조작 가능성 경고 구간.' },
    ],
  },
  altman_z: {
    label: 'Altman Z-Score', icon: '⚠️',
    what: '운전자본·이익잉여금·영업이익·시가총액·매출액 등 5개 재무비율을 가중합산해 "부도(파산) 가능성"을 예측하는 지표.',
    why: '1968년 발표 이후 기업 부도 예측 정확도가 학계에서 반복 검증된 지표입니다. 2.99 미만이면 안전지대를 벗어나 재무 리스크를 함께 점검해야 합니다.',
    levels: [
      { min: 2.99, label: '안전지대', color: 'green', desc: '파산 위험 낮음.' },
      { min: 1.81, label: '회색지대', color: 'gold', desc: '주의 관찰 필요.' },
      { min: -999, label: '위험지대', color: 'red', desc: '재무적 곤경 가능성 높음.' },
    ],
  },
  roic_wacc: {
    label: 'ROIC - WACC 스프레드', icon: '💎',
    what: 'ROIC(투하자본이익률)에서 WACC(자본조달비용)를 뺀 값. "자본을 굴려서 조달비용보다 얼마나 더 버는가"를 나타내는 가치창출 능력 지표.',
    why: '스프레드가 클수록 사업이 자본을 투입할 때마다 순가치를 만들어낸다는 뜻입니다. 워런 버핏이 강조하는 "경제적 해자(moat)"를 숫자로 표현한 지표입니다.',
    levels: [
      { min: 15, label: '우수', color: 'green', desc: '강력한 경제적 해자. 재투자할수록 가치 증가.' },
      { min: 5, label: '양호', color: 'gold', desc: '자본비용 상회. 정상적인 가치창출.' },
      { min: -999, label: '위험', color: 'red', desc: '자본비용도 못 버는 상태. 재투자가 가치파괴로 이어질 수 있음.' },
    ],
  },
  fcf_yield: {
    label: 'FCF Yield (잉여현금흐름 수익률)', icon: '💰',
    what: '잉여현금흐름(FCF = 영업현금흐름 - 설비투자, 여기선 스톡옵션비용까지 차감)을 시가총액으로 나눈 값. "주식 1주가 실제로 벌어들이는 현금"을 국채 이자처럼 수익률로 표현한 것.',
    why: 'FCF는 회계상 이익과 달리 조작이 어려운 "진짜 현금"입니다. FCF Yield가 국채금리보다 낮으면, 위험을 감수하고 주식을 살 유인이 부족하다는 뜻입니다.',
    levels: [
      { min: 3, label: '매력적', color: 'green', desc: '국채 대비 충분한 현금창출 프리미엄.' },
      { min: 0, label: '보통', color: 'gold', desc: '국채와 비슷하거나 소폭 우위.' },
      { min: -999, label: '주의', color: 'red', desc: '국채보다 낮은 현금수익률. 성장 기대가 밸류에이션을 정당화해야 함.' },
    ],
  },
  mom_12_1: {
    label: '가격 모멘텀 (12개월-1개월)', icon: '📈',
    what: '최근 12개월 수익률에서 가장 최근 1개월을 제외하고 계산한 값. 단기 노이즈를 걸러낸 "추세의 힘"을 측정합니다.',
    why: '학술 연구(Jegadeesh-Titman 1993)에서 모멘텀이 강한 종목이 이후에도 초과수익을 내는 경향이 반복 확인됐습니다. "달리는 말에 올라타라"는 격언의 통계적 근거입니다.',
    levels: [
      { min: 15, label: '강한 상승추세', color: 'green', desc: '기관 매수세 유입 가능성.' },
      { min: -5, label: '중립', color: 'gold', desc: '뚜렷한 추세 없음.' },
      { min: -999, label: '약세', color: 'red', desc: '하락추세 지속 중. 저가 매력만 보고 진입 시 추가 하락 위험.' },
    ],
  },
  erv_score: {
    label: '어닝 리비전 (실적 전망 수정)', icon: '✏️',
    what: '애널리스트들이 최근 실적 추정치를 상향 조정한 비율에서 하향 조정한 비율을 뺀 값.',
    why: '애널리스트 추정치 변화는 기업 내부 정보에 가장 민감하게 반응하는 선행지표 중 하나로, 상향 리비전이 몰리면 주가도 뒤따라 오르는 경향이 있습니다.',
    levels: [
      { min: 0.2, label: '상향 추세', color: 'green', desc: '펀더멘털 개선 시그널.' },
      { min: 0, label: '중립', color: 'gold', desc: '큰 변화 없음.' },
      { min: -999, label: '하향 추세', color: 'red', desc: '실적 눈높이 하향 중. 주가 역풍 가능.' },
    ],
  },
  pe: {
    label: 'PE (주가수익비율)', icon: '🔢',
    what: '주가를 주당순이익(EPS)으로 나눈 값. "이익 대비 주가가 몇 배인지" 나타내는 가장 기본적인 밸류에이션 지표.',
    why: '단독으로는 의미가 적고, 자기 자신의 과거 5년 밴드(백분위) 및 동종업계와 비교해야 고평가/저평가를 판단할 수 있습니다.',
    levels: [
      { max: 30, label: '낮은 백분위(저평가 구간)', color: 'green', desc: '자체 역사 밴드 하위권.' },
      { max: 70, label: '중간 백분위', color: 'gold', desc: '평균적인 수준.' },
      { max: 999, label: '높은 백분위(고평가 구간)', color: 'red', desc: '자체 역사 밴드 상위권. 성장 둔화 시 밸류에이션 조정 위험.' },
    ],
  },
};

// ── 방법론 가중치 (학술 검증) ─────────────────────
export const METHOD_WEIGHTS = {
  reverse_dcf: 0.18,    // Mauboussin-Rappaport
  ev_ebitda: 0.10,      // 섹터 상대 평가
  fcf_yield: 0.07,      // 국채 대비 절대 매력
  other_val: 0.05,      // PEG, EPV, SOTP
  piotroski: 0.18,      // Piotroski 2000 +7.5%p
  beneish: 0.10,        // 조작 탐지 게이트키퍼
  roic_wacc: 0.07,      // 가치 창출 능력
  momentum: 0.10,       // Jegadeesh-Titman 1993
  erv: 0.07,            // 어닝 리비전 모멘텀
  guru_13f: 0.08,       // Cohen et al. 2010 +6%p
};

// ── 200종목 유니버스 폴백 조회 ────────────────────
// STOCK_UNIVERSE(정밀 큐레이션 39종목)에 있으면 그 전체 데이터를,
// 없으면 lib/universe.js 메타 + 최소 스텁을 반환한다.
// 라이트 종목은 fair_value/piotroski 등 재무 원본이 없으므로
// null로 두고, 가격 기반 지표(PE/PEG/모멘텀/종합점수)만 계산된다.
export function getUniverseStock(symbol) {
  const fund = FUNDAMENTALS[symbol] || {};
  const curated = STOCK_UNIVERSE[symbol];
  if (curated) {
    // 큐레이션 종목: 자체 데이터 우선, 애널리스트 목표가 등 캐시 필드만 보충
    return {
      ...curated, symbol, lite: false,
      target_mean: fund.target_mean ?? null,
      target_high: fund.target_high ?? null,
      target_low: fund.target_low ?? null,
      num_analysts: fund.num_analysts ?? null,
      recommendation: fund.recommendation ?? null,
      peg_yahoo: fund.peg_yahoo ?? null,
      eps_growth_yoy: fund.eps_growth_yoy ?? null,
      debt_to_equity: fund.debt_to_equity ?? null,
      current_ratio: fund.current_ratio ?? null,
      roa: fund.roa ?? null,
    };
  }

  const meta = universeMeta(symbol);
  return {
    symbol,
    name: symbol,
    nameEn: symbol,
    flag: '🇺🇸',
    sector: meta?.sector || '기타',
    category: meta?.category || null,
    type: 'universe',
    lite: true,
    fair_value: null, fair_low: null, fair_high: null,
    eps_ttm: null, revenue_ttm: null,
    fcf_annual: null, sbc_annual: null, shares_out: null, net_cash: null,
    piotroski: null, beneish_m: null, altman_z: null,
    roic: null, wacc: null,
    mom_12_1: null, erv_score: null,
    rev_growth_accel: null, gm_trend: null,
    rule_of_40: null, tam_penetration: null,
    guru_cost: null, guru_cost_type: null, guru_note: null,
    segments: [], key_risk: null, key_oppty: null,
    pe_hist_avg_5y: null, pe_hist_min_5y: null, pe_hist_max_5y: null,
    // 재무 캐시 병합 (Yahoo quoteSummary 공시 기반, build_fundamentals.mjs로 갱신)
    rev_growth_yoy: fund.rev_growth_yoy ?? null,
    eps_growth_yoy: fund.eps_growth_yoy ?? null,
    gross_margin: fund.gross_margin ?? null,
    op_margin: fund.op_margin ?? null,
    roa: fund.roa ?? null,
    roe: fund.roe ?? null,
    current_ratio: fund.current_ratio ?? null,
    debt_to_equity: fund.debt_to_equity ?? null,
    target_mean: fund.target_mean ?? null,
    target_high: fund.target_high ?? null,
    target_low: fund.target_low ?? null,
    num_analysts: fund.num_analysts ?? null,
    recommendation: fund.recommendation ?? null,
    peg_yahoo: fund.peg_yahoo ?? null,
  };
}
